name: Workflow

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hi
      - run: python -V
      - run: pwd
      - run: ls
